In [1]:
import torch
import torch.nn as nn
import pandas as pd
import matplotlib.pyplot as plt
from tensorflow import keras
from keras.models import Model
from keras import Input
from keras.layers import Dense,Lambda
from tensorflow.keras.utils import plot_model
from keras import backend as K
from sklearn.preprocessing import StandardScaler
import matplotlib
import numpy as np
import graphviz
import plotly
import plotly.express as px
import sys
import os



In [57]:
!pip3 install plotly --user


[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
file = pd.read_csv("C:\\Users\\Lights\\Desktop\\ZEDI CODE\\rnn\\Data\\D12_M_GG_F_WM.csv")

In [3]:
file

Unnamed: 0            Time(hms)  Vrms_AN_avg  Irms_A_avg  Frequency_avg  \
0              0  12-02-2023 09:40:00      241.976    0.889882        49.9510   
1              1  12-02-2023 09:40:01      241.974    0.888205        49.9500   
2              2  12-02-2023 09:40:02      242.125    0.886671        49.9487   
3              3  12-02-2023 09:40:03      242.171    0.887079        49.9482   
4              4  12-02-2023 09:40:04      241.807    0.882004        49.9465   
...          ...                  ...          ...         ...            ...   
3797        3797  12-02-2023 12:40:14      244.545    8.900040        50.1583   
3798        3798  12-02-2023 12:40:15      244.397    8.894520        50.1567   
3799        3799  12-02-2023 12:40:16      244.797    8.907830        50.1554   
3800        3800  12-02-2023 12:40:17      244.593    8.901700        50.1538   
3801        3801  12-02-2023 12:40:18      244.798    8.907650        50.1537   

      PowerP_Total_avg  PfFwdRev_Total_avg    V_x   I_x     GGP  PF_x    V_y  \
0              168.589           -0.782935  241.4  0.04     1.8  0.19  241.3   
1              168.490           -0.783957  242.1  0.04     1.7  0.18  241.3   
2              168.831           -0.786411  241.9  0.04     1.8  0.19  241.1   
3              169.041           -0.786877  241.9  0.04     1.8  0.19  240.8   
4              168.078           -0.788080  241.6  0.04     1.8  0.19  241.0   
...                ...                 ...    ...   ...     ...   ...    ...   
3797          2175.680           -0.999643  234.0  8.76  2051.0  1.00  250.6   
3798          2173.020           -0.999641  234.4  8.78  2057.4  1.00  250.8   
3799          2179.900           -0.999672  233.9  8.76  2048.7  1.00  250.8   
3800          2176.540           -0.999656  234.3  8.77  2054.7  1.00  250.5   
3801          2179.800           -0.999648  234.3  8.77  2054.7  1.00  250.9   

      I_y    FP  PF_y      V     I  W|MP    PF  
0     0.4  63.9  0.66  241.2  0.26   0.0  0.00  
1     0.4  63.9  0.66  241.5  0.04   2.9  0.28  
2     0.4  63.8  0.66  241.4  0.05   3.6  0.33  
3     0.4  63.4  0.66  241.8  0.04   3.4  0.32  
4     0.4  63.2  0.66  241.8  0.04   3.4  0.32  
...   ...   ...   ...    ...   ...   ...   ...  
3797  0.1   8.5  0.33  250.7  0.04   2.5  0.24  
3798  0.1   8.5  0.33  250.4  0.04   2.4  0.23  
3799  0.1   8.5  0.33  250.9  0.04   2.4  0.23  
3800  0.1   8.4  0.32  250.9  0.04   2.4  0.23  
3801  0.1   8.6  0.33  250.6  0.04   2.5  0.24  

[3802 rows x 19 columns]

In [4]:
file.drop(columns=["Vrms_AN_avg","Irms_A_avg","PfFwdRev_Total_avg","V_x","I_x","PF_x","V_y","I_y","PF_y","V","I","PF"],inplace=True)

In [5]:
file.drop(columns=["Unnamed: 0"],inplace=True)

In [6]:
file

Time(hms)  Frequency_avg  PowerP_Total_avg     GGP    FP  W|MP
0     12-02-2023 09:40:00        49.9510           168.589     1.8  63.9   0.0
1     12-02-2023 09:40:01        49.9500           168.490     1.7  63.9   2.9
2     12-02-2023 09:40:02        49.9487           168.831     1.8  63.8   3.6
3     12-02-2023 09:40:03        49.9482           169.041     1.8  63.4   3.4
4     12-02-2023 09:40:04        49.9465           168.078     1.8  63.2   3.4
...                   ...            ...               ...     ...   ...   ...
3797  12-02-2023 12:40:14        50.1583          2175.680  2051.0   8.5   2.5
3798  12-02-2023 12:40:15        50.1567          2173.020  2057.4   8.5   2.4
3799  12-02-2023 12:40:16        50.1554          2179.900  2048.7   8.5   2.4
3800  12-02-2023 12:40:17        50.1538          2176.540  2054.7   8.4   2.4
3801  12-02-2023 12:40:18        50.1537          2179.800  2054.7   8.6   2.5

[3802 rows x 6 columns]

In [7]:
file.drop(columns=["FP","W|MP"],inplace=True)

In [8]:
file

Time(hms)  Frequency_avg  PowerP_Total_avg     GGP
0     12-02-2023 09:40:00        49.9510           168.589     1.8
1     12-02-2023 09:40:01        49.9500           168.490     1.7
2     12-02-2023 09:40:02        49.9487           168.831     1.8
3     12-02-2023 09:40:03        49.9482           169.041     1.8
4     12-02-2023 09:40:04        49.9465           168.078     1.8
...                   ...            ...               ...     ...
3797  12-02-2023 12:40:14        50.1583          2175.680  2051.0
3798  12-02-2023 12:40:15        50.1567          2173.020  2057.4
3799  12-02-2023 12:40:16        50.1554          2179.900  2048.7
3800  12-02-2023 12:40:17        50.1538          2176.540  2054.7
3801  12-02-2023 12:40:18        50.1537          2179.800  2054.7

[3802 rows x 4 columns]

In [9]:
file.drop(columns=["Frequency_avg"],inplace=True)

In [10]:
file

Time(hms)  PowerP_Total_avg     GGP
0     12-02-2023 09:40:00           168.589     1.8
1     12-02-2023 09:40:01           168.490     1.7
2     12-02-2023 09:40:02           168.831     1.8
3     12-02-2023 09:40:03           169.041     1.8
4     12-02-2023 09:40:04           168.078     1.8
...                   ...               ...     ...
3797  12-02-2023 12:40:14          2175.680  2051.0
3798  12-02-2023 12:40:15          2173.020  2057.4
3799  12-02-2023 12:40:16          2179.900  2048.7
3800  12-02-2023 12:40:17          2176.540  2054.7
3801  12-02-2023 12:40:18          2179.800  2054.7

[3802 rows x 3 columns]

In [11]:
# file["Time(hms)"]=file["Time(hms)"].strftime("%d-%m-%y %H:%M:%S")
file["Time(hms)"]=pd.to_datetime(file["Time(hms)"],format="%d-%m-%Y %H:%M:%S",dayfirst=True)

In [12]:
file['h']=file["Time(hms)"].dt.hour
file['m']=file["Time(hms)"].dt.minute
file['s']=file["Time(hms)"].dt.second

In [13]:
file

Time(hms)  PowerP_Total_avg     GGP   h   m   s
0    2023-02-12 09:40:00           168.589     1.8   9  40   0
1    2023-02-12 09:40:01           168.490     1.7   9  40   1
2    2023-02-12 09:40:02           168.831     1.8   9  40   2
3    2023-02-12 09:40:03           169.041     1.8   9  40   3
4    2023-02-12 09:40:04           168.078     1.8   9  40   4
...                  ...               ...     ...  ..  ..  ..
3797 2023-02-12 12:40:14          2175.680  2051.0  12  40  14
3798 2023-02-12 12:40:15          2173.020  2057.4  12  40  15
3799 2023-02-12 12:40:16          2179.900  2048.7  12  40  16
3800 2023-02-12 12:40:17          2176.540  2054.7  12  40  17
3801 2023-02-12 12:40:18          2179.800  2054.7  12  40  18

[3802 rows x 6 columns]

In [14]:
file1=file.copy()

In [15]:
mains = file[["Time(hms)","PowerP_Total_avg","h","m","s"]]
GG = file[["Time(hms)","GGP","h","m","s"]]

In [16]:
mains

Time(hms)  PowerP_Total_avg   h   m   s
0    2023-02-12 09:40:00           168.589   9  40   0
1    2023-02-12 09:40:01           168.490   9  40   1
2    2023-02-12 09:40:02           168.831   9  40   2
3    2023-02-12 09:40:03           169.041   9  40   3
4    2023-02-12 09:40:04           168.078   9  40   4
...                  ...               ...  ..  ..  ..
3797 2023-02-12 12:40:14          2175.680  12  40  14
3798 2023-02-12 12:40:15          2173.020  12  40  15
3799 2023-02-12 12:40:16          2179.900  12  40  16
3800 2023-02-12 12:40:17          2176.540  12  40  17
3801 2023-02-12 12:40:18          2179.800  12  40  18

[3802 rows x 5 columns]

In [17]:
GG

Time(hms)     GGP   h   m   s
0    2023-02-12 09:40:00     1.8   9  40   0
1    2023-02-12 09:40:01     1.7   9  40   1
2    2023-02-12 09:40:02     1.8   9  40   2
3    2023-02-12 09:40:03     1.8   9  40   3
4    2023-02-12 09:40:04     1.8   9  40   4
...                  ...     ...  ..  ..  ..
3797 2023-02-12 12:40:14  2051.0  12  40  14
3798 2023-02-12 12:40:15  2057.4  12  40  15
3799 2023-02-12 12:40:16  2048.7  12  40  16
3800 2023-02-12 12:40:17  2054.7  12  40  17
3801 2023-02-12 12:40:18  2054.7  12  40  18

[3802 rows x 5 columns]

In [18]:
file1

Time(hms)  PowerP_Total_avg     GGP   h   m   s
0    2023-02-12 09:40:00           168.589     1.8   9  40   0
1    2023-02-12 09:40:01           168.490     1.7   9  40   1
2    2023-02-12 09:40:02           168.831     1.8   9  40   2
3    2023-02-12 09:40:03           169.041     1.8   9  40   3
4    2023-02-12 09:40:04           168.078     1.8   9  40   4
...                  ...               ...     ...  ..  ..  ..
3797 2023-02-12 12:40:14          2175.680  2051.0  12  40  14
3798 2023-02-12 12:40:15          2173.020  2057.4  12  40  15
3799 2023-02-12 12:40:16          2179.900  2048.7  12  40  16
3800 2023-02-12 12:40:17          2176.540  2054.7  12  40  17
3801 2023-02-12 12:40:18          2179.800  2054.7  12  40  18

[3802 rows x 6 columns]

In [19]:
mainsp=np.array(file1["PowerP_Total_avg"]).reshape(-1,1)
ggp=np.array(file1["GGP"]).reshape(-1,1)

In [20]:
mainsp

array([[ 168.589],
       [ 168.49 ],
       [ 168.831],
       ...,
       [2179.9  ],
       [2176.54 ],
       [2179.8  ]])

In [21]:
ggp

array([[1.8000e+00],
       [1.7000e+00],
       [1.8000e+00],
       ...,
       [2.0487e+03],
       [2.0547e+03],
       [2.0547e+03]])

In [22]:
sca=StandardScaler()
sMainsP=sca.fit_transform(mainsp)
sGGP=sca.fit_transform(ggp)


In [23]:
sMainsP

array([[-0.98648178],
       [-0.98659089],
       [-0.98621507],
       ...,
       [ 1.23018932],
       [ 1.22648625],
       [ 1.23007911]])

In [24]:
print("mains p mean ",np.mean(sMainsP))
print("mains p std ",np.std(sMainsP))

print("ggp mean",np.mean(sGGP))
print("ggp std ",np.std(sGGP))

mains p mean  -5.980370211552658e-17
mains p std  1.0
ggp mean 1.1960740423105316e-16
ggp std  1.0


In [ ]:
def sampl_frm_lat(mean,sigma,latent_dim):
    
    z_mean,z_sigma=mean,sigma
    
    epsilon=K.random_normal(shape=(K.shape(z_mean)[0],latent_dim),mean=0.,stddev=1.)
    
    lat= z_mean+z_sigma*epsilon
    
    return lat
    